# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSpoty():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_spoty(self):
    self.driver.get("https://www.spotify.com/co/signup/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.ID, "email").click()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.ID, "email")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("oiloiloio@hotmail.com")
    self.driver.find_element(By.ID, "confirm").click()
    self.driver.find_element(By.ID, "confirm").send_keys("oiloiloio@hotmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("oiloiloio@hotmail.com")
    self.driver.find_element(By.ID, "displayname").click()
    self.driver.find_element(By.ID, "displayname").send_keys("pepito")
    self.driver.find_element(By.ID, "day").click()
    self.driver.find_element(By.ID, "day").send_keys("09")
    self.driver.find_element(By.ID, "month").click()
    dropdown = self.driver.find_element(By.ID, "month")
    dropdown.find_element(By.XPATH, "//option[. = 'Noviembre']").click()
    self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(12)").click()
    self.driver.find_element(By.ID, "year").click()
    self.driver.find_element(By.ID, "year").send_keys("1997")
    self.driver.find_element(By.CSS_SELECTOR, ".Radio-fatlcr-0:nth-child(2) > .Indicator-sc-16vj7o8-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".Indicator-sc-11vkltc-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fivrVz").click()
    self.driver.find_element(By.CSS_SELECTOR, ".jSRKEf").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".jSRKEf").text == "Confirma que no eres un robot."
  
